### ISSUE TITLE
Editor-only entities

### ISSUE THREAD

**Issue by snake-biscuits** [MRVN-Radiant/MRVN-Entities#7]
Earlier today I copied `simulacrum/` into [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant)'s `install/gamepacks/` (locally)
While making sure I wasn't replacing anything defined in the previous `entities.ent` for each game, I noticed `func_occluder`

This entity is not added to the `.bsp`'s entities when compiled, but instead flags geo for occlusion meshes[^remap_r1o][^remap_r2][^remap_r5]
I moved `func_occluder` to `editor.ent` to preserve it
Shortly afterward I realised `editor.ent` could hold `prop_static`, `func_detail`, maybe even `func_instance`[^vdc]

[MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) would detect these entities in `remap`[^remap_r1o][^remap_r2][^remap_r5] & compile them into the appropriate `.bsp` lumps
Any `editor.ent` / Internal Entities would need to be hard-coded into [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant)
So maybe `editor.ent` might be better off as part of [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) directly

[^vdc]: [Valve Developer Community](https://developer.valvesoftware.com/wiki/Main_Page) - [Category: Internal Entities](https://developer.valvesoftware.com/wiki/Category:Internal_entities)
[^remap_r1o]: [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) on GitHub - [tools/remap/source/titanfall/titanfall.cpp:187](https://github.com/MRVN-Radiant/MRVN-Radiant/blob/a2082088b1f5b9c82e086c43d9e3bb5710ed2e9c/tools/remap/source/titanfall/titanfall.cpp#L187)
[^remap_r2]: [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) on GitHub - [tools/remap/source/titanfall2/titanfall2.cpp:201](https://github.com/MRVN-Radiant/MRVN-Radiant/blob/a2082088b1f5b9c82e086c43d9e3bb5710ed2e9c/tools/remap/source/titanfall2/titanfall2.cpp#L201)
[^remap_r5]: [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) on GitHub - [tools/remap/source/apex_legends/apex_legends.cpp:167](https://github.com/MRVN-Radiant/MRVN-Radiant/blob/a2082088b1f5b9c82e086c43d9e3bb5710ed2e9c/tools/remap/source/apex_legends/apex_legends.cpp#L167)

**Comment by snake-biscuits** [comment]
Whether or not we add this depends on #6
`editor.ent` could be populated by `pilot/*.json` with `Block` set to `editor`, as a special case

Though since Titanfall 2 has over 200 entities[^r2], adding more `.json` to `pilot/r2/` would be a lot

[^r2]: [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) on GitHub - [Titanfall 2 Entities List](https://github.com/MRVN-Radiant/MRVN-Entities/issues/2)

**Comment by snake-biscuits** [comment]
> Any `editor.ent` / Internal Entities would need to be hard-coded into [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant)
> So maybe `editor.ent` might be better off as part of [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) directly

@F1F7Y thoughts?

I think the tools in [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) could be useful for copying some editor/compiler-only entity definitions
But automating a build of `editor.ent` would be more work
Keeping `editor.ent` up-to-date with `remap` from a separate repo would also be a huge pain.

Pretty sure maintaining a `editor.ent` for each game as part of [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) seems like the smarter move tbh.
Just want to write out the thought process out in writing to see if there's other opinions.

If / when [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) gets added to [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) w/ a pull request we can prob discuss this more

**Comment by snake-biscuits** [comment]
> If / when [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) gets added to [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) w/ a pull request we can prob discuss this more

atm I'm fairly confident I haven't removed any functionality, but I haven't done any serious testing.
Compiling some zoos from [MRVN-Resouce-Pack](https://github.com/MRVN-Radiant/MRVN-Resource-Pack/issues/1) should do.
The [current entity definitions in MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant/blob/main/games/Titanfall2.game/Titanfall2/entities.ent) don't cover much more than [`mp_base`](https://github.com/MRVN-Radiant/MRVN-Resource-Pack/blob/main/Titanfall2/maps/mp_base.map) rn anyway.

I should probably test ziplines and stuff first tho.
Maybe even gather up a few `.map` files from the Northstar Discord

Since we can't really automate testing on compile maps I'll need to work out some kind of QA checklist.
(Tho maybe `npc_pilots` & vscript could be used for some things)

**Comment by F1F7Y** [comment]
> I think the tools in [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) could be useful for copying some editor/compiler-only entity definitions But automating a build of `editor.ent` would be more work Keeping `editor.ent` up-to-date with `remap` from a separate repo would also be a huge pain.

The plan is to add [MRVN-Entities](https://github.com/MRVN-Radiant/MRVN-Entities) to [MRVN-Radiant](https://github.com/MRVN-Radiant/MRVN-Radiant) and considering we ship game/entity definitions, radiant and remap together I dont think keeping entity definitions up to date with remap would be hard.

Theoretically all we need to do now is to verify entity keyvalues, no?

Also regarding editor support for special entities I'd like those to be plugins. Barebones radiant shouldnt have hardcoded game specific features.

**Comment by snake-biscuits** [comment]
I've decided to go with the filename `radiant.ent` (using `"Block": "radiant"` in `.json`)
`editor.ent` was too close to the other filenames imo

Also wrote a quick & dirty `func_occluder.json` so we have definitions for all ents present in MRVN-Radiant rn

**Comment by snake-biscuits** [comment]
Might look into things like "changing brushes to `func_occluder` set texture to `tools/occluder`" etc. in Radiant later

> Also regarding editor support for special entities I'd like those to be plugins. Barebones radiant shouldnt have hardcoded game specific features.

I was mostly thinking about [`env_cubemap`](https://developer.valvesoftware.com/wiki/Env_cubemap) & compiled worldlights etc.
Entities that don't get compiled into entity lumps
Texture streaming probes for `.stbsp` will probably fall into a the same category

[`func_instance`](https://developer.valvesoftware.com/wiki/Func_instance) will definitely be better suited to a plugin though (e.g. [`ItEndsWithTens/Quinstance`](https://github.com/ItEndsWithTens/Quinstance))
There's a lot that can be done with instances in-editor too.

For example, Hammer++ allows for the quick creation of instances without opening a new tab[^h++]
And since Radiant only allows for a single map tab afaik, working with instances would be extremely difficult without this feature.
I could be wrong though, CoD2's example levels (that ship with CoD2Radiant) use a lot of instances.

[^h++]: [Hammer++ features](https://ficool2.github.io/HammerPlusPlus-Website/features.html)

**Comment by snake-biscuits** [comment]
I would like to use `func_instance` to construct the sdk / zoos for MRVN-Resource-Pack.
Could speed up things like blocking out ai frontlines for attrition etc.
Or we do an Apex Legends and copy paste the same buildings from colony everywhere (eden does this in r2)
